# Generated by Django 4.2.9 on 2026-03-13 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_id', models.CharField(max_length=10, verbose_name='주 식별자(월요일)')),
                ('study_seconds', models.PositiveIntegerField(default=0, verbose_name='취준 시간(초)')),
                ('ent_seconds', models.PositiveIntegerField(default=0, verbose_name='엔터 시간(초)')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='주간 점수(0~50)')),
                ('study_stage', models.PositiveSmallIntegerField(default=1, verbose_name='취준 단계(1~5)')),
                ('ratio_score', models.PositiveSmallIntegerField(default=0, verbose_name='비율 점수(1~10)')),
                ('streak_achieved', models.BooleanField(default=False, verbose_name='스트릭 달성 여부')),
                ('streak_count_after', models.PositiveIntegerField(default=0, verbose_name='리셋 후 스트릭')),
                ('reset_at', models.DateTimeField(auto_now_add=True, verbose_name='리셋 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_resets', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '주간 리셋',
                'verbose_name_plural': '주간 리셋 목록',
                'db_table': 'tb_weekly_reset',
                'ordering': ['-week_id'],
                'unique_together': {('user', 'week_id')},
            },
        ),
        migrations.CreateModel(
            name='TimerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('study', '취업 준비'), ('ent', '엔터테인먼트')], max_length=10, verbose_name='활동 유형')),
                ('started_at', models.DateTimeField(verbose_name='시작 시각')),
                ('ended_at', models.DateTimeField(verbose_name='종료 시각')),
                ('duration_seconds', models.PositiveIntegerField(verbose_name='지속 시간(초)')),
                ('week_id', models.CharField(db_index=True, max_length=10, verbose_name='주 식별자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_records', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '타이머 기록',
                'verbose_name_plural': '타이머 기록 목록',
                'db_table': 'tb_timer_record',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'week_id'], name='tb_timer_re_user_id_f0e851_idx'), models.Index(fields=['user', 'started_at'], name='tb_timer_re_user_id_530e41_idx')],
            },
        ),
    ]
