# Generated by Django 4.2.9 on 2026-03-13 05:08

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='닉네임')),
                ('streak_criteria', models.PositiveSmallIntegerField(default=80, help_text='주간 목표 대비 이 비율 이상 달성하면 스트릭 +1', verbose_name='스트릭 달성 기준(%)')),
                ('streak_count', models.PositiveIntegerField(default=0, verbose_name='현재 스트릭(주)')),
                ('goal_daily_seconds', models.PositiveIntegerField(default=14400, verbose_name='일별 목표(초)')),
                ('goal_weekly_seconds', models.PositiveIntegerField(default=90000, verbose_name='주별 목표(초)')),
                ('last_reset_week', models.DateField(blank=True, null=True, verbose_name='마지막 리셋 주')),
                ('notif_goal', models.BooleanField(default=True, verbose_name='목표 달성 알림')),
                ('notif_remind', models.BooleanField(default=True, verbose_name='미달성 독려 알림')),
                ('notif_balance_warn', models.BooleanField(default=True, verbose_name='잔고 부족 경고')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저 목록',
                'db_table': 'tb_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
